// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using storiesappapi.Helpers;

namespace storiesappapi.Entities
{
    public partial class StoriesDBContext : DbContext
    {
        public StoriesDBContext()
        {
        }

        public StoriesDBContext(DbContextOptions<StoriesDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<stories> stories { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(DbHelper.CS);
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<stories>(entity =>
            {
                entity.Property(e => e.createdat).HasDefaultValueSql("(getdate())");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}