// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace storiesappapi.Entities
{
    public partial class stories
    {
        [Key]
        public int id { get; set; }
        [StringLength(200)]
        public string plot { get; set; }
        [StringLength(200)]
        public string writer { get; set; }
        public int upvotes { get; set; }
        public bool editing { get; set; }
        public DateTime createdat { get; set; }
        public DateTime? updatedat { get; set; }
    }
}